/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tour;

/**
 *
 * @author acer
 */

import database.DBconnect;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import tour.main;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;



public final class tour_package_manage_in extends javax.swing.JInternalFrame {

    
     Connection con = null;
    PreparedStatement pst = null; 
    ResultSet rs = null ; 
    String path ;
    String m_path;
    
    /**
     * Creates new form tour_package_manage_in
     */
    public tour_package_manage_in() {
        initComponents();
   
        
         con = DBconnect.connect();
        
        //load table 
        tableload();
       
      
    }
    
    
    
      public void tableload(){
        
        String sql = " select  package_ID ,name  , rate ,type ,description,image  from package "  ;
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
    }

      public void rest(){
          
          jTextField1.setText("");
          jTextArea1.setText("");
          
      }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(1056, 668));
        setVerifyInputWhenFocusTarget(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(90, 120, 183));
        jPanel3.setPreferredSize(new java.awt.Dimension(1056, 668));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setVerifyInputWhenFocusTarget(false);
        jPanel3.setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(330, 310, 700, 170);

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jPanel3.add(jTextField5);
        jTextField5.setBounds(340, 160, 320, 30);

        jButton3.setBackground(new java.awt.Color(68, 145, 162));
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(440, 210, 110, 30);

        jPanel1.setBackground(new java.awt.Color(90, 120, 183));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type  ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 190, 60, 29);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(140, 130, 150, 30);

        jToggleButton1.setBackground(new java.awt.Color(68, 145, 162));
        jToggleButton1.setText("Delete");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(70, 450, 110, 30);

        jButton2.setBackground(new java.awt.Color(68, 145, 162));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 400, 110, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Description ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 260, 100, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rate  ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 130, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name  ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 60, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 30, 40, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(140, 20, 150, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 250, 150, 130);

        jButton5.setBackground(new java.awt.Color(68, 145, 162));
        jButton5.setText("Add");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 400, 120, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(140, 70, 150, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Normal", " " }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(140, 190, 150, 30);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(10, 20, 310, 510);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Package Details ");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(370, 80, 270, 50);

        jPanel4.setBackground(new java.awt.Color(90, 120, 183));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Add Imgae ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tour/Untitled-1.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setOpaque(true);

        jButton4.setBackground(new java.awt.Color(68, 145, 162));
        jButton4.setText("Add Image");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(680, 10, 350, 290);

        jButton7.setBackground(new java.awt.Color(68, 145, 162));
        jButton7.setText("Add Location ");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(400, 510, 120, 40);

        jButton1.setBackground(new java.awt.Color(68, 145, 162));
        jButton1.setText("view list");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(590, 510, 130, 40);

        jButton6.setBackground(new java.awt.Color(68, 145, 162));
        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(760, 510, 130, 40);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1040, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 System.out.println(path) ;
        int x =  JOptionPane.showConfirmDialog(null,"Do you want to Update" );

        if (x==0 ) {

            try {
                String Uid  = jLabel7.getText();

                String it160_Uname = jTextField1.getText() ;
                String it160_Urate = jComboBox1.getSelectedItem().toString();
                String it160_Utype = jComboBox2.getSelectedItem().toString();
                String it160_Udis = jTextArea1.getText();
                
              
                if(path==null || path == ""){
                        
                System.out.println(m_path) ;
                }
                
                else {
                     m_path  = path.replace("\\", "@");
                }
                
                String Update_sql = "update package set name='"+ it160_Uname+"' , rate ='"+it160_Urate +"' , type ='"+it160_Utype +"' , description ='"+it160_Udis+"',image='"+m_path+"' where package_ID = '"+Uid+"'";

                pst = con.prepareStatement(Update_sql);
                pst.execute() ;
                tableload();

            }
            catch (SQLException ex) {
                System.out.println(ex) ;
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked

        int x =  JOptionPane.showConfirmDialog(null,"Do you want to delete  " );

        if (x==0 ) {
            try {
                String package_id = jLabel7.getText();
                String delete_sql = "delete from package where package_ID ='"+package_id+"' " ;
                pst = con.prepareStatement(delete_sql);
                pst.execute() ;
                tableload();
                Restttt();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }

        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton1MouseClicked
  
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
         int r = jTable1.getSelectedRow();
        String id = jTable1.getValueAt(r,0).toString();
        String name = jTable1.getValueAt(r,1).toString();
         
        String rate  = jTable1.getValueAt(r,2).toString();
        String type  = jTable1.getValueAt(r,3).toString();
        String description   = jTable1.getValueAt(r,4).toString();
       m_path  = jTable1.getValueAt(r,5).toString();
        jTextField1.setText(name);
        jComboBox2.setSelectedItem(type );
        jTextArea1.setText(description);
        jComboBox1.setSelectedItem(rate );
        jLabel7.setText(id);
       
        
      if(!"NO".equals(m_path)){
       m_path = m_path.replace("@", "//");
         jLabel9.setIcon(ResiziseImage(m_path));
          System.out.println(m_path);
       
        }
      else{
          m_path ="C:\\Users\\Akila Sachin\\Desktop\\terra\\FInal Final\\PACKAGE p\\icon\\Untitled-1.jpg";
          jLabel9.setIcon(ResiziseImage(m_path));
      }
       



        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String Sname= jTextField5.getText();
         String sql = " select  package_ID ,name  , rate ,type ,description  from package  where name like  '%"+Sname+"%'"  ;
        
         try {
              pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
              jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             
         } catch (SQLException ex) {
             Logger.getLogger(tour_package_manage_in.class.getName()).log(Level.SEVERE, null, ex);
         }
            
           


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


         // TODO add your handling code here:
        JFileChooser file= new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File SelectedFile= file.getSelectedFile();
            path=SelectedFile.getAbsolutePath();
            jLabel9.setIcon(ResiziseImage(path));
            
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Select");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    int clickCount = 0 ; 
    
    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
      
        
        if(clickCount ==0){
        
    JFrame parent = new JFrame();

    JOptionPane.showMessageDialog(parent, "If you need to search a package  ... \n" + "Enter your package name");        
        }
        clickCount++;
            

// TODO add your handling code here:
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
   
        String tem = jTextField1.getText();
        
             
              
                       
           if(tem.isEmpty())
      {
           JOptionPane.showMessageDialog(null, "Please enter Package Nmae", "Error", JOptionPane.INFORMATION_MESSAGE);
      }
           else if ("".equals(path) || path == null){
          JOptionPane.showMessageDialog(null, "Add Image", "Error", JOptionPane.INFORMATION_MESSAGE);
      }
        
           else {
        
         String it160_name = jTextField1.getText() ;
        String it160_rate = jComboBox1.getSelectedItem().toString();
        String it160_type = jComboBox2.getSelectedItem().toString();
        String it160_dis = jTextArea1.getText();
        String m_path  = path.replace("\\", "@");

        System.out.println(it160_name);

        try {
            String it160_g = "INSERT INTO package (name,rate,type,description ,	image ) values ('"+it160_name+"','"+it160_rate+"','"+it160_type+"','"+it160_dis+"','"+m_path+"')";
            pst =con.prepareStatement(it160_g);
            pst.execute();

            //load table
            tableload();
            Restttt();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println(ex);
        }
           }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

             tour_package_list_ln pl = new tour_package_list_ln();                         
                    JDesktopPane n =getDesktopPane();
                    n.add(pl);
                    pl.show();
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked

                       String sql = " select max(package_ID) from package "  ;
            String id = null;
      
              
            try{
                
                
                int loopnumber =0;
                 Statement stmt = con.createStatement();
             rs = stmt.executeQuery(sql);
          
           // pst = con.prepareStatement(sql);
           // rs = pst.executeQuery();
            
           
        
            while (rs.next()) {
          id = rs.getString("max(package_ID)");
        
         System.out.println(id);
      
             
            
            }
            
         }
            catch (SQLException ex) {
          //  System.out.println(ex);
        }
     
                      tour_package_package_in pe = new tour_package_package_in(id);                         
                    JDesktopPane n =getDesktopPane();
                    n.add(pe);
                    pe.show();
                    this.dispose();




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    public ImageIcon ResiziseImage (String ImagePath){
        ImageIcon myimage=new ImageIcon(ImagePath);
        Image img=myimage.getImage();
        Image newimg=img.getScaledInstance(jLabel9.getWidth(),jLabel9.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newimg);
        return image;
    }
    
    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            jLabel7.setText("");
                 jTextField1.setText("") ;
                jComboBox1.setSelectedItem("1");
              jComboBox2.setSelectedItem("1") ;
                jTextArea1.setText("") ;
 m_path ="C:\\Users\\Akila Sachin\\Desktop\\terra\\FInal Final\\PACKAGE p\\icon\\Untitled-1.jpg";
          jLabel9.setIcon(ResiziseImage(m_path));


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    
   public void Restttt() {
        jLabel7.setText("");
                 jTextField1.setText("") ;
                jComboBox1.setSelectedItem("1");
              jComboBox2.setSelectedItem("1") ;
                jTextArea1.setText("") ;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
