/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tour;

/**
 *
 * @author acer
 */

import database.DBconnect;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;

public class tour_vehicle_manage_ln extends javax.swing.JInternalFrame {

    
     Connection con = null;
    PreparedStatement pst = null; 
     ResultSet rs = null ;
    
      String path ;
       String m_path  ; 
    /**
     * Creates new form tour_vehicle_manage_ln
     */
    public tour_vehicle_manage_ln() {
        initComponents();
        
          con = DBconnect.connect();
        tableload();
        
        
    }

    
       public void tableload(){
        
        String sql = " select  vehicle_id  ,name  , type,rate , fuel_type ,ac_cost,per_km_cost,sunroof,driver_l,driver_number,image  from vehicle "  ;
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(90, 120, 183));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 720));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(90, 120, 183));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Number");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 20, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Driver Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Rate");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 140, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Fuel Type");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 180, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("AC Cost");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 220, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("per km Cost");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 260, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Driver Number");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 380, 140, 30);

        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(160, 340, 170, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(160, 20, 170, 30);

        jTextField3.setToolTipText("");
        jTextField3.setBorder(null);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(160, 100, 170, 30);

        jTextField5.setToolTipText("Add more 4 ");
        jTextField5.setBorder(null);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(160, 220, 170, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(160, 300, 170, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(160, 140, 170, 30);

        jButton1.setBackground(new java.awt.Color(68, 145, 162));
        jButton1.setText("Delete");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(230, 440, 90, 30);

        jButton2.setBackground(new java.awt.Color(68, 145, 162));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 440, 90, 30);

        jButton3.setBackground(new java.awt.Color(68, 145, 162));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(130, 440, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Name ");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 60, 110, 30);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(160, 60, 170, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Sunroof");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 300, 140, 30);

        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField7);
        jTextField7.setBounds(160, 260, 170, 30);

        jTextField9.setBorder(null);
        jTextField9.setMinimumSize(new java.awt.Dimension(6, 22));
        jPanel2.add(jTextField9);
        jTextField9.setBounds(160, 380, 170, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Driver Licence");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 340, 140, 30);

        jComboBox3.setBackground(new java.awt.Color(90, 120, 183));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Diesel " }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(160, 180, 170, 30);

        jButton6.setBackground(new java.awt.Color(68, 145, 162));
        jButton6.setText("Location Details");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(110, 520, 150, 30);

        jButton7.setBackground(new java.awt.Color(68, 145, 162));
        jButton7.setText("Home");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(30, 480, 130, 30);

        jButton8.setBackground(new java.awt.Color(68, 145, 162));
        jButton8.setText("Guider Details");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(190, 480, 120, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 10, 340, 580);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 2", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 340, 680, 210);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Manage Vehicles ");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(390, 60, 280, 50);

        jTextField8.setBorder(null);
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(350, 150, 320, 30);

        jButton5.setBackground(new java.awt.Color(68, 145, 162));
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(420, 210, 100, 30);

        jPanel3.setBackground(new java.awt.Color(90, 120, 183));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Add Image ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tour/car.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);

        jButton4.setBackground(new java.awt.Color(68, 145, 162));
        jButton4.setText("Add Images");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(690, 20, 340, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String tem = jTextField9.getText();
         String tem1 = jTextField2.getText();
           String tem2 = jTextField5.getText();
             String tem3 = jTextField7.getText();
               String tem4 = jTextField9.getText();
               String tem5 = jTextField1.getText();
               
           if(tem.isEmpty() || tem1.isEmpty() || tem2.isEmpty() || tem3.isEmpty() || tem4.isEmpty())
      {
           JOptionPane.showMessageDialog(null, "Please enter All Data", "Error", JOptionPane.INFORMATION_MESSAGE);
      }
      else if(!tem.matches ("[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]") ||  tem.length() !=10 ){
          JOptionPane.showMessageDialog(null, "Contact Numbershould have 10 digits only.", "Error", JOptionPane.INFORMATION_MESSAGE);
       }
      else if (!tem5.matches ("[A-Z]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]")){
          JOptionPane.showMessageDialog(null, "Driver Licence should have 8 digits  and first letter in capital .", "Error", JOptionPane.INFORMATION_MESSAGE);
      }
      else if (!tem3.matches ("[0-9]+[0-9]")){
          JOptionPane.showMessageDialog(null, "per km Cost should have minimum 2 digits .", "Error", JOptionPane.INFORMATION_MESSAGE);
      }
           else if (!tem2.matches ("[0-9]+[0-9]")){
          JOptionPane.showMessageDialog(null, "AC Cost should have minimum 2 digits .", "Error", JOptionPane.INFORMATION_MESSAGE);
      }
              else if ("".equals(path) || path == null){
          JOptionPane.showMessageDialog(null, "Add Image", "Error", JOptionPane.INFORMATION_MESSAGE);
      }
        
       else {
        String it160_number = jTextField2.getText();
        String it160_name = jTextField6.getText();
        String it160_type = jTextField3.getText();
        String it160_rate = jComboBox2.getSelectedItem().toString();
        String it160_fuel = jComboBox3.getSelectedItem().toString();
        String ac_cost = jTextField5.getText();
        String per_ac_cost = jTextField7.getText();
        String it_sunroof = jComboBox1.getSelectedItem().toString();
        String driver_L = jTextField1.getText();
        String driver_numbers = jTextField9.getText();  
        String m_path  = path.replace("\\", "@");
        
        String it160_g = "INSERT INTO vehicle (vehicle_id,name,type,rate,fuel_type,ac_cost,per_km_cost,sunroof,driver_l,driver_number,image) values ('"+it160_number +"','"+it160_name+"','"+it160_type+"','"+it160_rate+"','"+it160_fuel+"','"+ac_cost+"','"+per_ac_cost+"','"+it_sunroof+"','"+driver_L+"','"+driver_numbers+"','"+m_path+"')";
        try {
            pst =con.prepareStatement(it160_g);
            pst.execute();
            tableload();

            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println(ex);

        }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int x =  JOptionPane.showConfirmDialog(null,"Do you want to Update " );

        if (x==0 ) {

            try {
                String it160_number = jTextField2.getText();
                String it160_name = jTextField6.getText();
                String it160_type = jTextField3.getText();
                String it160_rate = jComboBox2.getSelectedItem().toString();
                String it160_fuel = jComboBox3.getSelectedItem().toString();
                String ac_cost = jTextField5.getText();
                String per_ac_cost = jTextField7.getText();
                String it_sunroof = jComboBox1.getSelectedItem().toString();
                  String driver_numbers = jTextField9.getText();   
                    String driver_l  = jTextField1.getText();
                   //  String m_path  = path.replace("\\", "@");
                     
                     
                if(path==null || path == ""){
                        
                System.out.println(m_path) ;
                }
                
                else {
                     m_path  = path.replace("\\", "@");
                }
                     
                     
                     
                     
                String Update_sql = "update vehicle set  name ='"+it160_name +"' , type ='"+it160_type +"' , rate = '"+it160_rate+"',fuel_type ='"+it160_fuel+"',ac_cost='"+ ac_cost+"' ,per_km_cost = '"+ per_ac_cost+"',sunroof='"+it_sunroof+"',driver_number ='"+driver_numbers+"', driver_l ='"+driver_l+"',image='"+m_path+"'  where vehicle_ID = '"+it160_number+"'";
                pst = con.prepareStatement(Update_sql);
                pst.execute() ;
                tableload();
            } catch (SQLException ex) {
                System.out.println(ex);
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 
        int r = jTable1.getSelectedRow();
        String id = jTable1.getValueAt(r,0).toString();
        String name = jTable1.getValueAt(r,1).toString();

        String type  = jTable1.getValueAt(r,2).toString();
        String rate  = jTable1.getValueAt(r,3).toString();
        String fuel_type   = jTable1.getValueAt(r,4).toString();
        String  ac_cost   = jTable1.getValueAt(r,5).toString();
        String per_km_cost =jTable1.getValueAt(r,6).toString();
        String sunroof = jTable1.getValueAt(r,7).toString();
          String d_number = jTable1.getValueAt(r,8).toString();
        String p_number = jTable1.getValueAt(r,9).toString();
        String P_image  = jTable1.getValueAt(r,10).toString();
        jTextField2.setText(id);
        jTextField6.setText(name);
        jTextField3.setText(type);
        jComboBox2.setSelectedItem(rate);
        jComboBox3.setSelectedItem(fuel_type);
       jTextField7.setText(per_km_cost);
        jTextField5.setText(ac_cost);
        jTextField1.setText(d_number );
        jComboBox1.setSelectedItem(sunroof);
        jTextField9.setText(p_number) ;
        
        
        
        
        
         if(!"NO".equals(P_image)){
       m_path = P_image.replace("@", "//");
         jLabel1.setIcon(ResiziseImage(m_path));
       
        }
      else{
          m_path ="C:\\Users\\Akila Sachin\\Desktop\\terra\\FInal Final\\PACKAGE p\\icon\\car.jpg";
          jLabel1.setIcon(ResiziseImage(m_path));
      }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

            
         // TODO add your handling code here:
        JFileChooser file= new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Images", "jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File SelectedFile= file.getSelectedFile();
            path=SelectedFile.getAbsolutePath();
            jLabel1.setIcon(ResiziseImage(path));
            
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Select");
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed


          String Sname= jTextField8.getText();
         String sql = " select  vehicle_id  ,name  , type,rate , fuel_type ,ac_cost,per_km_cost,sunroof,driver_l  from vehicle   where vehicle_id  like  '%"+Sname+"%'"  ;
        
         try {
              pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
              jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             
         } catch (SQLException ex) {
             Logger.getLogger(tour_package_manage_in.class.getName()).log(Level.SEVERE, null, ex);
         }
            



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked


         int x =  JOptionPane.showConfirmDialog(null,"Do you want to delete  " );

        if (x==0 ) {
            try {
                String vehicle_id = jTextField2.getText();
                String delete_sql = "delete from vehicle where vehicle_id ='"+vehicle_id+"' " ;
                pst = con.prepareStatement(delete_sql);
                pst.execute() ;
                tableload();
            } catch (SQLException ex) {
                  System.out.println(ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

        int clickCount = 0 ;
    
    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked

          if(clickCount ==0){
        
    JFrame parent = new JFrame();

    JOptionPane.showMessageDialog(parent, "If you need to search a vehicle  ... \n" + "Enter your vehicle number ");        
        }
        clickCount++;


        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked

   tour_guider_manage_ln  pe = new tour_guider_manage_ln();                         
                    JDesktopPane n =getDesktopPane();
                    n.add(pe);
                    pe.show();
                    this.dispose();



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked


            tour_locaation_manage_ln  pe = new tour_locaation_manage_ln();                         
                    JDesktopPane n =getDesktopPane();
                    n.add(pe);
                    pe.show();
                    this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
            this.dispose();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    
      public ImageIcon ResiziseImage (String ImagePath){
        ImageIcon myimage=new ImageIcon(ImagePath);
        Image img=myimage.getImage();
        Image newimg=img.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newimg);
        return image;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
