/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeMath.round;
import database.DBconnect;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dell
 */
public class Emp_Payment extends javax.swing.JInternalFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form Allowance
     */
    public Emp_Payment() {
        initComponents();
        con=DBconnect.connect();
        
        getContentPane().setBackground(new Color(90, 120, 183));
        jPanel1.setOpaque(false);
        jPanel2.setOpaque(false);
        jPanel3.setOpaque(false);
        
        tableload();
    }
     public void tableload()
    {
        try{
            String sql="SELECT e.Empid,e.Name,e.Job,e.bsal as Basic_Salary,p.Gloss_Salary,p.Total_Deductions,p.Net_Salary from empdetails e,emp_payment p where e.empid=p.empid";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            Emp_pay.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e)
        {
            System.out.println("Error in getting data from db");
            System.out.println(e.getMessage());
        }
    }
     
     public boolean checkId(String id) {
        
        try{
            String sql = "Select 1 from empdetails where empid = ?";  
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, id);
            ResultSet rs = ps.executeQuery();

            return rs.next();
            
        }
        catch (Exception e)
        {
            System.out.println("Error in checking empID "+e);
        }
        return false;
        
    }
      public void Reset()
    {
      search_txt.setText("");
      id_lbl.setText("");
      name_lbl.setText("");
      job_lbl.setText("");
      bsal_lbl.setText("");    
      otr_lbl.setText("");
      toth_lbl.setText("");
      otamt_lbl.setText("");
      doj_lbl.setText("");
      med_box.setText("");
      bonus_box.setText("");
      sc_box.setText("");
      travel_box.setText("");
      rent_box.setText("");
      holiday_box.setText("");                                        
      nopay_box.setText("");
      insur_box.setText("");
      deathd_box.setText("");
      leave_box.setText("");
      epf_lbl.setText("");
      etf_lbl.setText(""); 
      gsal_lbl.setText("");
      totald_lbl.setText("");
      netsal_lbl.setText("");                                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        Submit_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        job_lbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bsal_lbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        otr_lbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        toth_lbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        otamt_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        doj_lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        med_box = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        bonus_box = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        sc_box = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        travel_box = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        rent_box = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        holiday_box = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        gsal_lbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Emp_pay = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        epf_lbl = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        etf_lbl = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        nopay_box = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        insur_box = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        deathd_box = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        leave_box = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        totald_lbl = new javax.swing.JLabel();
        Update_button = new javax.swing.JButton();
        NewRecord_button = new javax.swing.JButton();
        Clear_Button = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        netsal_lbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1060, 750));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee ID");

        search_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_txtKeyTyped(evt);
            }
        });

        Submit_button.setBackground(new java.awt.Color(68, 145, 162));
        Submit_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Submit_button.setForeground(new java.awt.Color(255, 255, 255));
        Submit_button.setText("Search");
        Submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Submit_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        id_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        id_lbl.setForeground(new java.awt.Color(255, 255, 255));
        id_lbl.setText("                     ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Job Title");

        job_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        job_lbl.setForeground(new java.awt.Color(255, 255, 255));
        job_lbl.setText("                   ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Basic Salary");

        bsal_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bsal_lbl.setForeground(new java.awt.Color(255, 255, 255));
        bsal_lbl.setText("                ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee ID");

        name_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        name_lbl.setForeground(new java.awt.Color(255, 255, 255));
        name_lbl.setText("                     ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("OT Rate");

        otr_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        otr_lbl.setForeground(new java.awt.Color(255, 255, 255));
        otr_lbl.setText("                     ");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total OT Hrs");

        toth_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        toth_lbl.setForeground(new java.awt.Color(255, 255, 255));
        toth_lbl.setText("                 ");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("OT amount");

        otamt_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        otamt_lbl.setForeground(new java.awt.Color(255, 255, 255));
        otamt_lbl.setText("                     ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Joined Date");

        doj_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        doj_lbl.setForeground(new java.awt.Color(255, 255, 255));
        doj_lbl.setText("                     ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(id_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(doj_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(otamt_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(toth_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(otr_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsal_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(job_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(id_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(job_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bsal_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(otr_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(toth_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(otamt_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(doj_lbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(85, 68, 162));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Allowance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Medical");

        med_box.setText("0");
        med_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                med_boxKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Bonus");

        bonus_box.setText("0");
        bonus_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bonus_boxKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Service Charge");

        sc_box.setText("0");
        sc_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sc_boxActionPerformed(evt);
            }
        });
        sc_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sc_boxKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Travel");

        travel_box.setText("0");
        travel_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                travel_boxKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Rent");

        rent_box.setText("0");
        rent_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rent_boxKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Holiday Pay");

        holiday_box.setText("0");
        holiday_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                holiday_boxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bonus_box, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(med_box)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(travel_box)
                            .addComponent(rent_box)
                            .addComponent(holiday_box)
                            .addComponent(sc_box))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(med_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(bonus_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(sc_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(travel_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(rent_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(holiday_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Gloss Salary");

        gsal_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gsal_lbl.setText("         ");

        Emp_pay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Emp_pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Emp_payMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Emp_pay);

        jPanel4.setBackground(new java.awt.Color(90, 120, 183));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deductions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 304));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("EPF");

        epf_lbl.setBackground(new java.awt.Color(90, 120, 183));
        epf_lbl.setText("                                                       ");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("ETF");

        etf_lbl.setText("                                                      ");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Loan");

        nopay_box.setText("0");
        nopay_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nopay_boxKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Insurance");

        insur_box.setText("0");
        insur_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                insur_boxKeyTyped(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Death Donations");

        deathd_box.setText("0");
        deathd_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deathd_boxKeyTyped(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Leaves");

        leave_box.setText("0");
        leave_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                leave_boxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nopay_box, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addComponent(insur_box)
                        .addComponent(deathd_box)
                        .addComponent(leave_box))
                    .addComponent(epf_lbl)
                    .addComponent(etf_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(epf_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(etf_lbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(nopay_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(insur_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(deathd_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(leave_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Total Deductions");

        totald_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        totald_lbl.setText("         ");

        Update_button.setBackground(new java.awt.Color(68, 145, 162));
        Update_button.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Update_button.setForeground(new java.awt.Color(255, 255, 255));
        Update_button.setText("Calculate");
        Update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_buttonActionPerformed(evt);
            }
        });

        NewRecord_button.setBackground(new java.awt.Color(68, 145, 162));
        NewRecord_button.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NewRecord_button.setForeground(new java.awt.Color(255, 255, 255));
        NewRecord_button.setText("New Record");
        NewRecord_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewRecord_buttonActionPerformed(evt);
            }
        });

        Clear_Button.setBackground(new java.awt.Color(68, 145, 162));
        Clear_Button.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Clear_Button.setForeground(new java.awt.Color(255, 255, 255));
        Clear_Button.setText("Clear");
        Clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_ButtonActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Net Salary");

        netsal_lbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        netsal_lbl.setText("         ");

        jButton1.setBackground(new java.awt.Color(68, 145, 162));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(68, 145, 162));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Pay Slip");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel32))))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gsal_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totald_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(netsal_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Clear_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Update_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NewRecord_button))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(gsal_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Clear_Button)
                            .addComponent(NewRecord_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Update_button))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(totald_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel33)
                                    .addComponent(netsal_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sc_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sc_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sc_boxActionPerformed

    private void Submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_buttonActionPerformed

        String id=search_txt.getText();
        boolean empIdValid=checkId(id);
        
        if(empIdValid==true)
        {
            try{
                String sql="SELECT * from empdetails where empid = '"+id+"'";
                pst=con.prepareStatement(sql);
                rs=pst.executeQuery();
           // allo_w.setModel(DbUtils.resultSetToTableModel(rs)); 
            
                if(rs.next())
                {                       
                     String add1 =rs.getString("empid");
                    id_lbl.setText(add1);
                    name_lbl.setText(rs.getString("name"));
                    job_lbl.setText(rs.getString("job"));
                    bsal_lbl.setText(rs.getString("bsal"));
                    doj_lbl.setText(rs.getString("doj"));
            
                    double Salary =rs.getDouble("bsal");
                    
                    Calendar c = Calendar.getInstance();
                    int No_DaysM = c.getActualMaximum(Calendar.DAY_OF_MONTH);
                    int No_hours_month=No_DaysM*8;

                    double OTrr=(Salary/No_hours_month)*1.5;
                    double OTr = Math.round(OTrr*100.0)/100.0;
                    String x = String.valueOf(OTr);
                    otr_lbl.setText(x);
            
                    double epf=(Salary/100)*8;
                    double etf=(Salary/100)*3;
            
                    epf_lbl.setText(String.valueOf(epf));
                    etf_lbl.setText(String.valueOf(etf));
                    
                    try{
                     String cdate=new SimpleDateFormat("MM/dd/yyyy").format(Calendar.getInstance().getTime());
                     Calendar cc = Calendar.getInstance();   // this takes current date
                     cc.set(Calendar.DAY_OF_MONTH, 1);
                     String pdate=new SimpleDateFormat("MM/dd/yyyy").format(cc.getTime()); 
               // System.out.println(pdate);                            
                     PreparedStatement statement = con.prepareStatement("SELECT sum(Oth) from attendance where empid = '"+id+"' and Outdate between '"+pdate+"'and '"+cdate+"'");
                     ResultSet result = statement.executeQuery();
                     result.next();             
                     String summ = result.getString(1);
                     System.out.println(summ);
                     
                     double No_of_oth= Double.parseDouble(summ);
                     double Ot_amount=No_of_oth*OTr;
                     
                     String OTAMT=String.valueOf(Ot_amount);
                     
                     toth_lbl.setText(summ);
                     otamt_lbl.setText(OTAMT);
                    }
                catch(Exception e )
                {
                    JOptionPane.showMessageDialog(null,"Attendance has not been marked ","Alert",JOptionPane.WARNING_MESSAGE);
                    System.out.println("Error getting OT hours in searching btn"+e);
                    return;
                }
                    
                    
                    
                    tableload();
                }                                                                       
            }
            catch(Exception e)
            {
                System.out.println("Error in searching at allow");
                System.out.println(e.getMessage());
            }
            try{
                String qq="SELECT * from emp_payment where empid = '"+id+"'";
                pst=con.prepareStatement(qq);
                rs=pst.executeQuery();
                
                if(rs.next())
                {   
                    //name_lbl.setText(rs.getString("name"));
                    med_box.setText(rs.getString("Medical"));
                    bonus_box.setText(rs.getString("Bonus"));
                    sc_box.setText(rs.getString("Service_Charge"));
                    travel_box.setText(rs.getString("Travel"));
                    rent_box.setText(rs.getString("rent"));
                    holiday_box.setText(rs.getString("other"));                                        
                    nopay_box.setText(rs.getString("nopay"));
                    insur_box.setText(rs.getString("Insurance"));
                    deathd_box.setText(rs.getString("Death_donations"));
                    leave_box.setText(rs.getString("Lateness"));
                    gsal_lbl.setText(rs.getString("Gloss_Salary"));
                    totald_lbl.setText(rs.getString("Total_Deductions"));
                    netsal_lbl.setText(rs.getString("Net_Salary"));
                }
                
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        else
        {
             JOptionPane.showMessageDialog(null,"Invalid Employee ID","Alert",JOptionPane.WARNING_MESSAGE);
        }
            
        
    }//GEN-LAST:event_Submit_buttonActionPerformed

    private void Emp_payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Emp_payMouseClicked

     
    }//GEN-LAST:event_Emp_payMouseClicked

    private void Update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_buttonActionPerformed
        if(search_txt.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Employee Id");
               return;
        }
              
       if(med_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Medical allowances");
               return;
        }
       if(bonus_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Bonus");
               return;
        }
       if(sc_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Service Charge allowances");
               return;
        }
       if(travel_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Travel allowances");
               return;
        }
       if(rent_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Rent allowances");
               return;
        }
       if(holiday_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Holiday pay");
               return;
        }
       if(nopay_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Nopay Charges");
               return;
        }
       if(insur_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Insurance Charges");
               return;
        }
       if(deathd_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Death Donations");
               return;
        }
       if(leave_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Charges for Leaves");
               return;
        }
       
        String id=search_txt.getText();    
        double bsal=Double.parseDouble(bsal_lbl.getText());      
        //allowance
        double Otamount=Double.parseDouble(otamt_lbl.getText());
        double medical=Double.parseDouble(med_box.getText());
        double bonus=Double.parseDouble(bonus_box.getText());
        double service_ch=Double.parseDouble(sc_box.getText());
        double travel=Double.parseDouble(travel_box.getText());
        double rent=Double.parseDouble(rent_box.getText());
        double other=Double.parseDouble(holiday_box.getText());
        
        //deduct
        double epf=Double.parseDouble(epf_lbl.getText());
        double etf=Double.parseDouble(etf_lbl.getText());
        double nopay=Double.parseDouble(nopay_box.getText());
        double insurance=Double.parseDouble(insur_box.getText());
        double death_don=Double.parseDouble(deathd_box.getText());
        double lateness=Double.parseDouble(leave_box.getText());
        
        
        
        double gsal=bsal+Otamount+medical+bonus+service_ch+travel+rent+other;
        double totaldeduct=epf+etf+nopay+insurance+death_don+lateness;
        double netsal=gsal-totaldeduct;
        
       // double netsal=round(netsal_t,2);
        
        String Glossal=String.valueOf(gsal);
        String Totald=String.valueOf(totaldeduct);
        String Netsal=String.valueOf(netsal);
        gsal_lbl.setText(Glossal);
        totald_lbl.setText(Totald);
        netsal_lbl.setText(Netsal);
        
        String Bsal=bsal_lbl.getText();
        String otr=otr_lbl.getText();
        String toth=toth_lbl.getText();
        String totalOtA=otamt_lbl.getText();
        String doj=doj_lbl.getText();
        String Toth=toth_lbl.getText();
        //allowance
        String uot=otamt_lbl.getText();
        String umedical=med_box.getText();
        String ubonus=bonus_box.getText();
        String uservice_ch=sc_box.getText();
        String utravel=travel_box.getText();
        String urent=rent_box.getText();
        String uother=holiday_box.getText();
        
        //deduct
        String uepf=epf_lbl.getText();
        String uetf=etf_lbl.getText();
        String unopay=nopay_box.getText();
        String uinsurance=insur_box.getText();
        String udeath_don=deathd_box.getText();
        String uleaves=leave_box.getText();
        
        //update emp_payment
        try{
            String q="Update emp_payment set Total_OTh='"+Toth+"',Total_OT_Amount='"+uot+"',OT_Rate='"+otr+"',Medical='"+umedical+"',Bonus='"+ubonus+"',Service_Charge='"+uservice_ch+"',Travel ='"+utravel+"',Rent='"+urent+"',Other='"+uother+"',epf='"+epf+"',etf='"+etf+"',Nopay='"+unopay+"',Insurance='"+uinsurance+"',Death_donations='"+udeath_don+"',Lateness='"+uleaves+"',Gloss_Salary='"+Glossal+"',Total_Deductions='"+Totald+"',Net_Salary='"+Netsal+"' where empid='"+id+"'";
            pst=con.prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Record Updated");
            tableload();
        }
        catch(Exception e)
        {
            System.out.println("Error in emp_payment cal"+e);
        }
        
        
        //process of creating all payroll table
        String cdate=new SimpleDateFormat("MM/dd/yyyy").format(Calendar.getInstance().getTime());
        String [] datep = cdate.split("/");
        String mm=datep[0];
        try
        {
            String d="select paid_date from emp_all_payments where empid='"+id+"'and  paid_date LIKE ?";
            pst=con.prepareStatement(d);
            pst.setString(1,mm + "%");
            rs=pst.executeQuery();
            //if record is there in emp_all_payments
            if(rs.next())
            {
                System.out.println("Record exists");
                String p_date=rs.getString("paid_date");
                String [] dateParts = p_date.split("/");
                String month= dateParts[0];
                int m=Integer.parseInt(month);
                
                int cmo=Calendar.getInstance().get(Calendar.MONTH)+1;
                //if same month then update emp_all_payments
                if(m==cmo)
                {                   
                    try{
                         String q="Update emp_all_payments set Total_OTh='"+Toth+"',Total_OT_Amount='"+uot+"',OT_Rate='"+otr+"',Medical='"+umedical+"',Bonus='"+ubonus+"',Service_Charge='"+uservice_ch+"',Travel ='"+utravel+"',Rent='"+urent+"',Other='"+uother+"',epf='"+epf+"',etf='"+etf+"',Nopay='"+unopay+"',Insurance='"+uinsurance+"',Death_donations='"+udeath_don+"',Lateness='"+uleaves+"',Gloss_Salary='"+Glossal+"',Total_Deductions='"+Totald+"',Net_Salary='"+Netsal+"' where empid='"+id+"'and paid_date LIKE ?";
                         pst=con.prepareStatement(q);
                         pst.setString(1,mm + "%");
                         pst.execute();
                        // JOptionPane.showMessageDialog(this,"all emp Updated");
                         
                    }
                    catch(Exception e)
                    {
                        System.out.println("Error in emp_all_payments update"+e);
                    }                                                           
                }
                //if month if diff create a new record emp_all_payments
                else
                {
                    try{            
                        String sqll="INSERT INTO emp_all_payments (paid_date,empid,OT_Rate,Total_OTh,Total_OT_Amount,DateOf_Join,Medical,Bonus,Service_Charge,Travel,Rent,Other,epf,etf,Nopay,Insurance,Death_donations,Lateness,Gloss_Salary,Total_Deductions,Net_Salary) values ('"+cdate+"','"+id+"','"+otr+"','"+toth+"','"+totalOtA+"','"+doj+"','"+medical+"','"+bonus+"','"+service_ch+"','"+travel+"','"+rent+"','"+other+"','"+epf+"','"+etf+"','"+nopay+"','"+insurance+"','"+death_don+"','"+lateness+"','"+Glossal+"','"+Totald+"','"+Netsal+"')";            
                        pst=con.prepareStatement(sqll);
                        pst.execute(); 
                        JOptionPane.showMessageDialog(this,"newly added to all payments coz month is diff");                    
                    }
                    catch(Exception e)
                    {
                        System.out.println("Error in inserting to emp_all_payments"+e);
                    }
                    
                }
                                               
            }
            //create a new record
            else
            {
                try{            
                    String sqll="INSERT INTO emp_all_payments (paid_date,empid,OT_Rate,Total_OTh,Total_OT_Amount,DateOf_Join,Medical,Bonus,Service_Charge,Travel,Rent,Other,epf,etf,Nopay,Insurance,Death_donations,Lateness,Gloss_Salary,Total_Deductions,Net_Salary) values ('"+cdate+"','"+id+"','"+otr+"','"+toth+"','"+totalOtA+"','"+doj+"','"+medical+"','"+bonus+"','"+service_ch+"','"+travel+"','"+rent+"','"+other+"','"+epf+"','"+etf+"','"+nopay+"','"+insurance+"','"+death_don+"','"+lateness+"','"+Glossal+"','"+Totald+"','"+Netsal+"')";            
                    pst=con.prepareStatement(sqll);
                    pst.execute(); 
                                       
                }
                catch(Exception e)
                {
                    System.out.println("Error in inserting to emp_all_payments"+e);
                }
            }
            
        }
        catch(Exception e)
        {
            System.out.println("error in calculate in all payroll"+e);
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_Update_buttonActionPerformed

    private void NewRecord_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewRecord_buttonActionPerformed
         if(search_txt.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Employee Id");
               return;
        }
                                           
       if(med_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Medical allowances");
               return;
        }
       if(bonus_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Bonus");
               return;
        }
       if(sc_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Service Charge allowances");
               return;
        }
       if(travel_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Travel allowances");
               return;
        }
       if(rent_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Rent allowances");
               return;
        }
       if(holiday_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Holiday Pay");
               return;
        }
       if(nopay_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Nopay Charges");
               return;
        }
       if(insur_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Insurance Charges");
               return;
        }
       if(deathd_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Death Donations");
               return;
        }
       if(leave_box.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Charges for Leaves");
               return;
        }
        
        
        String id=search_txt.getText();
        String name=name_lbl.getText();
        String job=job_lbl.getText();
        String bsal=bsal_lbl.getText();       
        String otr=otr_lbl.getText();
        String toth=toth_lbl.getText();
        String totalOtA=otamt_lbl.getText();
        String doj=doj_lbl.getText();
               
        //allowance       
        String medical=med_box.getText();
        String bonus=bonus_box.getText();
        String service_ch=sc_box.getText();
        String travel=travel_box.getText();
        String rent=rent_box.getText();
        String other=holiday_box.getText();
        
        //deduct
        String epf=epf_lbl.getText();
        String etf=etf_lbl.getText();
        String nopay=nopay_box.getText();
        String insurance=insur_box.getText();
        String death_don=deathd_box.getText();
        String lateness=leave_box.getText();
        
        String gsal=gsal_lbl.getText();
        String TotalD=totald_lbl.getText();
        String Netsal=netsal_lbl.getText();
       
        try{
            String ss = "Select 1 from emp_payment where empid = '"+id+"'"; 
            PreparedStatement ps = con.prepareStatement(ss);           
            ResultSet rs = ps.executeQuery();
            boolean result= rs.next();
            
            if(result!=true)
            {
            try{            
                String sql="INSERT INTO emp_payment (empid,OT_Rate,Total_OTh,Total_OT_Amount,DateOf_Join,Medical,Bonus,Service_Charge,Travel,Rent,Other,epf,etf,Nopay,Insurance,Death_donations,Lateness,Gloss_Salary,Total_Deductions,Net_Salary) values ('"+id+"','"+otr+"','"+toth+"','"+totalOtA+"','"+doj+"','"+medical+"','"+bonus+"','"+service_ch+"','"+travel+"','"+rent+"','"+other+"','"+epf+"','"+etf+"','"+nopay+"','"+insurance+"','"+death_don+"','"+lateness+"','"+gsal+"','"+TotalD+"','"+Netsal+"')";            
                pst=con.prepareStatement(sql);
                pst.execute(); 
                JOptionPane.showMessageDialog(this,"Successfully Inserted");
                tableload();
            }
            catch(Exception e)
            {
                 System.out.println("Error in inserting to Emp_payment"+e);
            }
            }
            else
                 JOptionPane.showMessageDialog(null,"Record already exists","Alert",JOptionPane.WARNING_MESSAGE);
                               
        }
        catch(Exception e)
        {
            System.out.println("Error in check empid of Emp_payment"+e);
        }



        
    }//GEN-LAST:event_NewRecord_buttonActionPerformed

    private void search_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_txtKeyTyped
       char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_search_txtKeyTyped

    private void med_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_med_boxKeyTyped
        char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_med_boxKeyTyped

    private void sc_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sc_boxKeyTyped
       char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_sc_boxKeyTyped

    private void travel_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_travel_boxKeyTyped
        char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_travel_boxKeyTyped

    private void rent_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rent_boxKeyTyped
       char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_rent_boxKeyTyped

    private void holiday_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_holiday_boxKeyTyped
       char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_holiday_boxKeyTyped

    private void nopay_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nopay_boxKeyTyped
        char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_nopay_boxKeyTyped

    private void insur_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insur_boxKeyTyped
        char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_insur_boxKeyTyped

    private void deathd_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deathd_boxKeyTyped
       char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_deathd_boxKeyTyped

    private void leave_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_leave_boxKeyTyped
        char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_leave_boxKeyTyped

    private void bonus_boxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonus_boxKeyTyped
        char c=evt.getKeyChar();
         
         if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACKSPACE) || (c== KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_bonus_boxKeyTyped

    private void Clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_ButtonActionPerformed
        Reset();
    }//GEN-LAST:event_Clear_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(search_txt.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Employee ID");
               return;
        }
        int y=JOptionPane.showConfirmDialog(null, "Do you want to delete ?");
        if(y==0)
        {
        String id=search_txt.getText(); 
        String q2="delete from emp_payment where empid='"+id+"'";           
            
        try{                           
                pst=con.prepareStatement(q2);
                pst.execute();
                JOptionPane.showMessageDialog(this,"Successfully deleted");
            
                //load table
                tableload();
                Reset();                  
        }
        catch(Exception e)
        {
                System.out.println("Error in deleting");
                System.out.println(e.getMessage());
                
        }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if(search_txt.getText().equals("")){
               JOptionPane.showMessageDialog(this,"Please enter Employee ID");
               return;
        }
        
        HashMap para =new HashMap();
        if(search_txt.getText().length()!=0)
        {
            para.put("empid",search_txt.getText());
            ReportView r=new ReportView("C:\\Users\\Akila Sachin\\Documents\\NetBeansProjects\\HMS\\src\\Employee\\ireportTest\\pay1\\pay22.jasper",para);
            r.setVisible(true);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_Button;
    private javax.swing.JTable Emp_pay;
    private javax.swing.JButton NewRecord_button;
    private javax.swing.JButton Submit_button;
    private javax.swing.JButton Update_button;
    private javax.swing.JTextField bonus_box;
    private javax.swing.JLabel bsal_lbl;
    private javax.swing.JTextField deathd_box;
    private javax.swing.JLabel doj_lbl;
    private javax.swing.JLabel epf_lbl;
    private javax.swing.JLabel etf_lbl;
    private javax.swing.JLabel gsal_lbl;
    private javax.swing.JTextField holiday_box;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JTextField insur_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel job_lbl;
    private javax.swing.JTextField leave_box;
    private javax.swing.JTextField med_box;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JLabel netsal_lbl;
    private javax.swing.JTextField nopay_box;
    private javax.swing.JLabel otamt_lbl;
    private javax.swing.JLabel otr_lbl;
    private javax.swing.JTextField rent_box;
    private javax.swing.JTextField sc_box;
    private javax.swing.JTextField search_txt;
    private javax.swing.JLabel totald_lbl;
    private javax.swing.JLabel toth_lbl;
    private javax.swing.JTextField travel_box;
    // End of variables declaration//GEN-END:variables
}
